# Generated by Django 2.2.6 on 2019-10-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_auto_20191024_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='market.Department', verbose_name='使用する学科'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='market.Status', verbose_name='状態'),
        ),
    ]
