# Generated by Django 2.2.6 on 2019-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_auto_20191019_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='image',
            field=models.ImageField(upload_to='textbooks', verbose_name='画像'),
        ),
    ]
