# Generated by Django 2.2.6 on 2019-10-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_auto_20191023_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbook',
            name='department',
            field=models.IntegerField(choices=[(1, '共通科目'), (2, '外国語科目'), (3, '健康余暇科学科目'), (4, '英語英文学科'), (5, '国際関係学科'), (6, '数学科'), (7, '情報科学科')], default=1, verbose_name='使用する学科'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='schoolyear',
            field=models.IntegerField(choices=[(1, '1年生'), (2, '2年生'), (3, '3年生'), (4, '4年生')], default=1, verbose_name='推奨学年'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='status',
            field=models.IntegerField(choices=[(1, '新品同様'), (2, '汚れ、折り線有り'), (3, '書き込み有り')], default=1, verbose_name='状態'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
