# Generated by Django 2.2.6 on 2019-10-23 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_auto_20191023_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbook',
            name='is_checked',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbook',
            name='schoolyear',
            field=models.IntegerField(choices=[('1年生', '1'), (2, '2年生'), (3, '3年生'), (4, '4年生')], default='1年生', verbose_name='推奨学年'),
        ),
    ]
