# Generated by Django 2.2.6 on 2019-10-23 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_auto_20191023_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbook',
            name='is_checked',
        ),
        migrations.AlterField(
            model_name='textbook',
            name='schoolyear',
            field=models.IntegerField(choices=[(1, '1年生'), (2, '2年生'), (3, '3年生'), (4, '4年生')], default=1, verbose_name='推奨学年'),
        ),
    ]
